Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength: # testing blocks usually have more than 25 lines
  Exclude:
    - 'spec/lib/log_parser/result_printer_spec.rb'